<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Browser atau aplikasi ini mungkin tidak aman</name>
   <tag></tag>
   <elementGuidId>5e6f7e01-0a0a-4be3-841d-00366fe68cfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.PrDSKc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53d779c5-67de-4a38-af90-08d55a173843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrDSKc</value>
      <webElementGuid>1765bf95-09bd-40c7-93a7-e5a286d3c146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browser atau aplikasi ini mungkin tidak aman.</value>
      <webElementGuid>d2da4ef8-4167-4945-b945-597e422929fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;view_container&quot;)/div[@class=&quot;zWl5kd&quot;]/div[@class=&quot;DRS7Fe bxPAYd k6Zj8d&quot;]/div[@class=&quot;pwWryf bxPAYd&quot;]/div[@class=&quot;Wxwduf Us7fWe JhUD8d&quot;]/div[@class=&quot;WEQkZc&quot;]/div[@class=&quot;bCAAsb&quot;]/form[1]/span[1]/section[@class=&quot;aTzEhb&quot;]/div[@class=&quot;CxRgyd&quot;]/div[1]/div[1]/div[@class=&quot;PrDSKc&quot;]</value>
      <webElementGuid>24cb71de-5fcb-4164-929f-05d971f55aaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_container']/div/div/div[2]/div/div/div/form/span/section/div/div/div/div</value>
      <webElementGuid>a8a46fa9-13db-42e9-ac45-6ccca4f465a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak dapat membuat Anda login'])[1]/following::div[9]</value>
      <webElementGuid>ecb4f376-a420-43c8-a5d5-086448680225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login dengan Google'])[1]/following::div[14]</value>
      <webElementGuid>abc54973-6323-4784-98dd-2f55b4743856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coba lagi'])[1]/preceding::div[5]</value>
      <webElementGuid>dd4479ce-552e-4129-b483-9b1ea11d6a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‪Afrikaans‬'])[1]/preceding::div[10]</value>
      <webElementGuid>b55a7d97-9c96-4b60-9a7f-3dec53ddd21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Browser atau aplikasi ini mungkin tidak aman.']/parent::*</value>
      <webElementGuid>c76a3c7b-3cae-4869-8cb3-a30808b3c424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div</value>
      <webElementGuid>ae756f02-0a98-40f3-ab15-01c209458da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Browser atau aplikasi ini mungkin tidak aman.' or . = 'Browser atau aplikasi ini mungkin tidak aman.')]</value>
      <webElementGuid>0c8363bb-2c92-43ea-b92a-ef5689ec7915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
