<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_How To Prepare for Your First UIUX Desig_b994ee</name>
   <tag></tag>
   <elementGuidId>0db855d0-207e-4a00-b222-6f1386403e56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='titleEventDetail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#titleEventDetail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6820073d-db95-4f68-ba23-e0e4e812bdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titleEventDetail</value>
      <webElementGuid>0b5d3a73-8d9f-441f-947d-40a3fff64907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How To Prepare for Your First UI/UX Design Career</value>
      <webElementGuid>8a7c39c2-063d-4629-b8b7-d5e25b09c8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleEventDetail&quot;)</value>
      <webElementGuid>76250786-b60e-42c8-8dbf-0d0670e6c120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='titleEventDetail']</value>
      <webElementGuid>bd21d5b9-2d49-4435-bcd2-baaae23d3802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventDetailBlock']/h1</value>
      <webElementGuid>972a2110-bcdb-4ae8-9372-e3ba1c3a5be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How To Prepare for Your First UI/UX Design Career'])[1]/following::h1[1]</value>
      <webElementGuid>107fc0ee-8068-4ff1-a7aa-5c66f356ef15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Events'])[1]/following::h1[1]</value>
      <webElementGuid>6fde013c-1f20-461b-a1e8-deff8d14fc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profesi ini lagi dicari oleh banyak perusahaan! Yups UI/UX adalah 2 hal yang berbeda.'])[1]/preceding::h1[1]</value>
      <webElementGuid>0a0b5964-cf71-4651-9f27-5d0485986993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b2f4b9f1-3f2d-4788-a201-6d91e6a7b825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'titleEventDetail' and (text() = 'How To Prepare for Your First UI/UX Design Career' or . = 'How To Prepare for Your First UI/UX Design Career')]</value>
      <webElementGuid>186105ea-bd3e-4316-8961-eb2e575f9245</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
