<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_UIUX Research  Design (Hands On With Figma)</name>
   <tag></tag>
   <elementGuidId>8600551f-64fa-48ab-966e-abbc283a78b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='titleEventDetail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#titleEventDetail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>35ea57cc-5ca5-49e3-9a61-900f7c64e5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titleEventDetail</value>
      <webElementGuid>fab22675-f00a-49b9-99ca-11c2805eb8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UI/UX Research &amp; Design (Hands On With Figma)</value>
      <webElementGuid>e2af17f5-0957-48c1-9125-78e1d14695ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleEventDetail&quot;)</value>
      <webElementGuid>44d7a20c-95f2-42e0-b9ea-a5f1d3b16776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='titleEventDetail']</value>
      <webElementGuid>0abff629-29aa-462e-a030-52e2855a7ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventDetailBlock']/h1</value>
      <webElementGuid>6489a80e-adce-400f-a378-2a983a051884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UI/UX Research &amp; Design (Hands On With Figma)'])[1]/following::h1[1]</value>
      <webElementGuid>0529361f-8672-4e90-92e3-45a533045e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Events'])[1]/following::h1[1]</value>
      <webElementGuid>194db35c-9c86-4c0d-8182-2887b2a96dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sabtu, 1 Oktober 2022'])[1]/preceding::h1[1]</value>
      <webElementGuid>9a06d12f-64e5-4053-951f-bb784a067cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>3cf1f35a-cdab-4b7e-a01e-df0a247e2161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'titleEventDetail' and (text() = 'UI/UX Research &amp; Design (Hands On With Figma)' or . = 'UI/UX Research &amp; Design (Hands On With Figma)')]</value>
      <webElementGuid>6147ee6e-a141-4f26-8272-c7379356f582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
