<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_box</name>
   <tag></tag>
   <elementGuidId>420bd189-9bcf-4174-9adb-db8474683ea9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='box']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9d167c3-3eb7-448e-b2e6-819e6391c793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>8d3ad457-0cd2-4436-a8e0-585c4d26868a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>67a555ca-b5a3-4504-9426-c329dbb6562a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:keyup</name>
      <type>Main</type>
      <value>onSearch</value>
      <webElementGuid>3281b88a-e810-424a-940f-adb20ebd814e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ca4edd5f-39ea-4928-9432-c308f1d32b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Skill apa yang ingin kamu kuasai ?</value>
      <webElementGuid>edff6ad0-4d79-4f20-a6c8-ecb6bfd49ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model.defer</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b7bf4973-34a2-4351-b67d-a37feead5846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box&quot;)</value>
      <webElementGuid>b6b4e586-fb9e-4f3f-80d7-6444dd0fde92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='box']</value>
      <webElementGuid>e34146b0-a52a-4c84-a8af-d6360a556cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-button']/input</value>
      <webElementGuid>0fec5d29-e54c-4443-b09a-f42f80ed18d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6f6c656f-b04c-46a8-9429-6674ef830f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'box' and @placeholder = 'Skill apa yang ingin kamu kuasai ?']</value>
      <webElementGuid>5275a5d5-9475-4ca4-9457-c8fb21c0a263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
