<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_box</name>
   <tag></tag>
   <elementGuidId>e19d3c9e-7d62-49d8-a228-029d2e6f8142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='box']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>770df099-261a-4f2b-a7ed-8411f72c3299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>957b8c76-2216-40f2-93d4-04127d2f3007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>e7cc2a52-aec8-48cc-87c6-d9f548d521ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:keyup</name>
      <type>Main</type>
      <value>onSearch</value>
      <webElementGuid>1e336437-d036-4417-b544-e97146d8b784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>914c1495-7223-448c-99fe-b16724d20043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Skill apa yang ingin kamu kuasai ?</value>
      <webElementGuid>6b3e164c-cf9a-4e1b-883d-5dd4fc64765c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model.defer</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6840be06-f6a6-48bc-a9bd-ea360b183d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box&quot;)</value>
      <webElementGuid>bbfcbc29-843a-4370-9901-5d39ce0065a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='box']</value>
      <webElementGuid>6f228440-46ae-4a6c-aa10-c2d52221895f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-button']/input</value>
      <webElementGuid>ed31f888-d54c-458e-950a-ed940bbea15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>5b5445bf-eced-479a-9cd2-9c98ec93c9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'box' and @placeholder = 'Skill apa yang ingin kamu kuasai ?']</value>
      <webElementGuid>5872af08-8912-42a5-9275-d201c69fd252</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
