<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChangeProfile_Calendar_SelectedDateLastRow</name>
   <tag></tag>
   <elementGuidId>610c727f-7b43-4eba-8a42-7555924bc215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>body > div.daterangepicker.ltr.single.auto-apply.opensright.show-calendar > div.drp-calendar.left.single > div.calendar-table > table > tbody > tr:nth-child(1) > td:nth-child(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[2]/div[1]/table/tbody/tr[6]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>body > div.daterangepicker.ltr.single.auto-apply.opensright.show-calendar > div.drp-calendar.left.single > div.calendar-table > table > tbody > tr:nth-child(1) > td:nth-child(6)</value>
      <webElementGuid>6320be84-4be6-44df-9a68-04de89737e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a5b4501b-f4a2-44a9-a6ca-316608606417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>available</value>
      <webElementGuid>f78ab627-7ef0-4687-90c5-affa93aa7b8a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
