<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Profile_rounded-circle author-box-picture</name>
   <tag></tag>
   <elementGuidId>16e12927-3ac8-4c35-aa93-3901275ecf64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/section/div/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle.author-box-picture</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>77a7f7f2-04be-482c-bbe4-fadeedfafba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>16813189-e5be-4587-9872-a7e2040f40a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/codingid-storage-bucket/storage/uploads/avatar/1680147982Pas Photo.png</value>
      <webElementGuid>38112d12-644d-4721-90c0-eef68fe5463c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle author-box-picture</value>
      <webElementGuid>71cf57f8-faaf-4416-9ec0-17ad89524ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-wrapper main-wrapper-1&quot;]/div[@class=&quot;main-content&quot;]/section[@class=&quot;section&quot;]/div[@class=&quot;section-body&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-12 col-md-12 col-lg-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row mt-4 align-items-end&quot;]/div[@class=&quot;col-lg-3 col-md-4 col-sm-12&quot;]/img[@class=&quot;rounded-circle author-box-picture&quot;]</value>
      <webElementGuid>33b05b82-4bc3-4b77-b637-c33558547e01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/section/div/div/div/div/div/div/div/img</value>
      <webElementGuid>4e7ccbf8-934f-4fe9-9dc8-1cd9771560af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='image']</value>
      <webElementGuid>50fa692c-d737-4f5c-8bf1-4700698ec592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fd8d5ad1-22a2-484d-a780-6cc039282dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'image' and @src = 'https://storage.googleapis.com/codingid-storage-bucket/storage/uploads/avatar/1680147982Pas Photo.png']</value>
      <webElementGuid>9c050bd2-362a-4d40-8a3a-0b4ed6601961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
