<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Events_searchInputEvent</name>
   <tag></tag>
   <elementGuidId>91de69af-d9e2-4b5d-a473-c6388bd4db21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchInputEvent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchInputEvent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8410a56e-96eb-4fb3-9dfe-59426743b94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchInputEvent</value>
      <webElementGuid>e9007bd5-0c68-40b1-9a19-385a08113bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d34d0c8d-3861-45d9-aec3-21886f49e3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>921711fa-bf3c-4621-ae63-df3048aebeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control searchinput</value>
      <webElementGuid>8e6fe113-024e-48a1-aa85-281725479697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>69dd4c2e-35b4-4cc6-aad7-acad6e11ae1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchInputEvent&quot;)</value>
      <webElementGuid>03b06456-e57e-4b7f-9b5b-462851a0a40f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchInputEvent']</value>
      <webElementGuid>b9e2da76-6a65-43e2-ab02-942547d28309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerEvent']/div/div/div[2]/input</value>
      <webElementGuid>faf0851e-015d-4c00-9784-6e05c08d6a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>33a7f29a-a1a6-4ccc-9ba6-b88a29e6ac34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchInputEvent' and @type = 'text' and @placeholder = '']</value>
      <webElementGuid>e644d3a6-a7d1-48e4-ad10-9723c88b0fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
